# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "7a545f80e0f00ca04cd959cedb3c1438cb218656d0484ecb36593b1c3b077ef4"  # change this!
  limiter: false  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
  cors_domains: ["*"]
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
search:
 formats:
  - html
  - json
